blog/urls.py
from django.urls import path
from django.urls.conf import include
from.views import *


app_name = 'blog'

urlpatterns = [
    path('article/',article_list, name='article_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',article_detail, name='article_detail'),
    path('<int:post_id>/share/',article_share, name='article_share')
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Article(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'),
                      ('published', 'Published')
                      )
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'year':self.publish.year, 'month':self.publish.month, 'day':self.publish.day, 'slug':self.slug})


class Comment(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article
from .forms import EmailPostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail


def article_list(request):
    object_list =  Article.objects.filter(status='published')
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:

        articles = paginator.page(1)
    except EmptyPage:

        articles = paginator.page(paginator.num_pages)
    context = {'page': page, 'articles': articles}
    return render(request, 'blog/article_list.html', context)


def article_detail(request, year, month, day, slug):
    article = get_object_or_404(Article, publish__year=year, publish__month=month,
                                publish__day=day, slug=slug, status='published')
    context = {'article': article}
    return render(request, 'blog/article_detail.html', context)




def article_share(request, post_id):
    
    articles = get_object_or_404(Article, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
            articles.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
            f"{articles.title}"
            message = f"Read {articles.title} at {post_url}\n\n" \
            f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'abayomi5991@gmail.com',
            [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {'articles': articles,'form': form,'sent': sent}
    return render(request, 'blog/share.html', context)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static  'css/blog.css' %}" rel="stylesheet">
</head>

<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog.</p>
    </div>
</body>

</html>

blog/templates/blog/article_detail.html
{% extends "base.html" %}
{% block title %} {{ article.title }} {% endblock %}
{% block content %}
<h1>{{ article.title }}</h1>
<p class="date"> Published {{ article.publish }} by {{ article.author }}</p>
{{ article.body|linebreaks }}
<p>
    <a href="{% url 'blog:article_share' article.id %}">
        Share this post
    </a>
</p>
{% endblock %}

blog/templates/blog/article_list.html
{% extends "base.html" %}
{% block title %} Article {% endblock %}
{% block content %}
<h1>Articles</h1>
{% for article in articles %}
<h2>
    <a href="{{ article.get_absolute_url }}">
        {{ article.title }}
    </a>
</h2>
<p class="date">
    Published {{ article.publish }} by {{ article.author }}
</p>
{{ article.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=articles %}
{% endblock %}

blog/templates/blog/share.html
{% extends "base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ articles.title }}" was successfully sent to {{form.cleaned_data.to}}.
</p>
{% else %}
<h1>Share "{{ articles.title }}" by e-mail</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>